name: Build and release to chrome store
on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn install
    - run: yarn build